import asyncio
import logging
from datetime import datetime
from pathlib import Path

import uvicorn
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse

from models import ScorePayload
from worker_models import WorkerRequest
from worker_service import call_worker
from xml_builder import build_musicxml
from harmonize import generate_variants

# ── Setup ─────────────────────────────────────────────────────────────────────

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s  %(levelname)-8s  %(name)s  %(message)s',
)
logger = logging.getLogger(__name__)

OUTPUT_DIR = Path(__file__).parent / 'output'
OUTPUT_DIR.mkdir(exist_ok=True)

# ── App ───────────────────────────────────────────────────────────────────────

app = FastAPI(
    title='Music Staff API',
    version='1.0.0',
    description='Accepts a score JSON from the React frontend and returns a MusicXML file.',
)

# Allow requests from the Vite dev server and preview server.
# Restrict allow_origins to specific domains in production.
app.add_middleware(
    CORSMiddleware,
    allow_origins=['*'],
    allow_methods=['GET', 'POST'],
    allow_headers=['*'],
)

# ── Endpoints ─────────────────────────────────────────────────────────────────

@app.get('/api/health', tags=['system'])
async def health_check() -> dict:
    """Liveness probe — returns server status and output directory path."""
    return {
        'status':     'ok',
        'output_dir': str(OUTPUT_DIR),
        'files':      len(list(OUTPUT_DIR.glob('*.xml'))),
    }


@app.post('/api/score/musicxml', status_code=201, tags=['score'])
async def convert_to_musicxml(payload: ScorePayload) -> dict:
    """
    Accept a validated score JSON, generate a MusicXML file, save it to disk.

    Request body — see ScorePayload schema (auto-generated Swagger docs at /docs).

    Returns:
        filename      — generated file name
        path          — absolute path on the server
        size_bytes    — file size
        download_url  — relative URL to fetch the file
    """
    try:
        xml_content = build_musicxml(payload)
    except Exception as exc:
        logger.exception('MusicXML generation failed')
        raise HTTPException(status_code=500, detail=f'XML generation failed: {exc}')

    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S_%f')
    filename  = f'score_{timestamp}.xml'
    filepath  = OUTPUT_DIR / filename

    filepath.write_text(xml_content, encoding='utf-8')
    size = filepath.stat().st_size

    logger.info('Generated %s  (%d bytes)', filename, size)

    return {
        'filename':     filename,
        'path':         str(filepath),
        'size_bytes':   size,
        'download_url': f'/api/score/download/{filename}',
    }


@app.get('/api/score/download/{filename}', tags=['score'])
async def download_musicxml(filename: str) -> FileResponse:
    """
    Download a previously generated MusicXML file by filename.

    Returns the file with Content-Disposition: attachment so the browser
    saves it instead of opening it inline.
    """
    # Reject any path traversal attempt
    safe_name = Path(filename).name
    if safe_name != filename or '..' in filename:
        raise HTTPException(status_code=400, detail='Invalid filename')

    filepath = OUTPUT_DIR / safe_name
    if not filepath.exists():
        raise HTTPException(status_code=404, detail=f'File not found: {safe_name}')

    return FileResponse(
        path=str(filepath),
        media_type='application/vnd.recordare.musicxml+xml',
        filename=safe_name,
        headers={'Content-Disposition': f'attachment; filename="{safe_name}"'},
    )


@app.post('/api/score/harmonize', status_code=201, tags=['score'])
async def harmonize_score(payload: ScorePayload) -> dict:
    """
    Accept a melody JSON and return three harmonization variants.

    Each variant contains:
      - id, name, description  — display metadata
      - filename, download_url — link to the saved MusicXML file
      - measures               — full score data for frontend Staff rendering

    The bass line is generated by a rule-based harmonizer using I / IV / V chords.
    """
    try:
        variants = generate_variants(payload, OUTPUT_DIR)
    except Exception as exc:
        logger.exception('Harmonization failed')
        raise HTTPException(status_code=500, detail=f'Harmonization failed: {exc}')

    logger.info('Harmonized: %d variants, %d measures', len(variants), len(payload.measures))
    return {'variants': variants}


@app.post('/api/worker/submit', status_code=200, tags=['worker'])
async def submit_worker_job(payload: WorkerRequest) -> dict:
    """
    Accept a worker-format request from the frontend, forward it to the
    C++ harmonisation engine via subprocess, and return the engine's response.

    The payload is validated by Pydantic then serialised verbatim (camelCase)
    and piped to harmonizer_worker.exe stdin. The worker's stdout (one JSON
    line) is parsed and returned to the caller.
    """
    logger.info('Worker job received  jobId=%s  mode=%s', payload.jobId, payload.mode)

    # Exclude None fields so optional settings (e.g. scaleMode for check_solution)
    # are not serialised as JSON null, which would confuse the C++ parser.
    raw = payload.model_dump(exclude_none=True)

    # call_worker blocks on subprocess I/O — run it in a thread so we don't
    # stall the async event loop during processing.
    return await asyncio.to_thread(call_worker, raw)


# ── Entry point ───────────────────────────────────────────────────────────────

if __name__ == '__main__':
    uvicorn.run('main:app', host='0.0.0.0', port=8080, reload=True)
